# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(LIBFILE_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALFILE_INCLUDE_DIRS)
   

find_library(LIBFILE_DEBUG_LIBRARY alfile_d)
find_library(LIBFILE_LIBRARY       alfile)


if (LIBFILE_DEBUG_LIBRARY)
  set(LIBFILE_LIBRARIES optimized;${LIBFILE_LIBRARY};debug;${LIBFILE_DEBUG_LIBRARY})
else()
  set(LIBFILE_LIBRARIES ${LIBFILE_LIBRARY})
endif()

set(LIBFILE_LIBRARIES ${LIBFILE_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBFILE DEFAULT_MSG
  LIBFILE_LIBRARIES
  LIBFILE_INCLUDE_DIRS
)
set(LIBFILE_PACKAGE_FOUND ${LIBFILE_FOUND} CACHE INTERNAL "" FORCE)
 
set(LIBFILE_DEPENDS "" CACHE INTERNAL "" FORCE)
 