# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(TOOLS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(ALTOOLS_INCLUDE_DIRS)
   

find_library(TOOLS_DEBUG_LIBRARY altools_d)
find_library(TOOLS_LIBRARY       altools)


if (TOOLS_DEBUG_LIBRARY)
  set(TOOLS_LIBRARIES optimized;${TOOLS_LIBRARY};debug;${TOOLS_DEBUG_LIBRARY})
else()
  set(TOOLS_LIBRARIES ${TOOLS_LIBRARY})
endif()

set(TOOLS_LIBRARIES ${TOOLS_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TOOLS DEFAULT_MSG
  TOOLS_LIBRARIES
  TOOLS_INCLUDE_DIRS
)
set(TOOLS_PACKAGE_FOUND ${TOOLS_FOUND} CACHE INTERNAL "" FORCE)
 
set(TOOLS_DEPENDS "" CACHE INTERNAL "" FORCE)
 