#ifndef __GENERATED_alproxies__
#define __GENERATED_alproxies__
#include <alproxies/almemoryproxy.h>
#include <alproxies/alresourcemanagerproxy.h>
#include <alproxies/alframemanagerproxy.h>
#include <alproxies/alvideodeviceproxy.h>
#include <alproxies/alphotocaptureproxy.h>
#include <alproxies/aldarknessdetectionproxy.h>
#include <alproxies/alaudiorecorderproxy.h>
#include <alproxies/alaudioplayerproxy.h>
#include <alproxies/almotionrecorderproxy.h>
#include <alproxies/alvisionrecognitionproxy.h>
#include <alproxies/albehaviormanagerproxy.h>
#include <alproxies/alredballtrackerproxy.h>
#include <alproxies/alloggerproxy.h>
#include <alproxies/alspeechrecognitionproxy.h>
#include <alproxies/alredballdetectionproxy.h>
#include <alproxies/albatteryproxy.h>
#include <alproxies/allandmarkdetectionproxy.h>
#include <alproxies/alconnectionmanagerproxy.h>
#include <alproxies/albonjourproxy.h>
#include <alproxies/alfacetrackerproxy.h>
#include <alproxies/alledsproxy.h>
#include <alproxies/alsonarproxy.h>
#include <alproxies/alnavigationproxy.h>
#include <alproxies/allaserproxy.h>
#include <alproxies/alaudiodeviceproxy.h>
#include <alproxies/allauncherproxy.h>
#include <alproxies/alvideorecorderproxy.h>
#include <alproxies/alsounddetectionproxy.h>
#include <alproxies/alvisiontoolboxproxy.h>
#include <alproxies/alsensorsproxy.h>
#include <alproxies/alpreferencesproxy.h>
#include <alproxies/alaudiosourcelocalizationproxy.h>
#include <alproxies/alfsrproxy.h>
#include <alproxies/alfacedetectionproxy.h>
#include <alproxies/albacklightingdetectionproxy.h>
#include <alproxies/alsentinelproxy.h>
#include <alproxies/alpythonbridgeproxy.h>
#include <alproxies/alfilemanagerproxy.h>
#include <alproxies/alrobotposeproxy.h>
#include <alproxies/alrobotpostureproxy.h>
#include <alproxies/alinfraredproxy.h>
#include <alproxies/alvisualcompassproxy.h>
#include <alproxies/dcmproxy.h>
#include <alproxies/altexttospeechproxy.h>
#include <alproxies/almotionproxy.h>
#include <alproxies/api.h>
#include <alproxies/networkinfo.h>
#endif
